### ISSUE TITLE
Evaluate DC/OS 1.10 and identify constructs required for API-M deployment 

### ISSUE THREAD

**Issue by imesh** [wso2/dcos-apim#1]
**Description:**
The previous set of WSO2 DC/OS resources [1] were created for DC/OS 1.7. Since then DC/OS has evolved quite a lot and has added new features such as overlay networking, internal routing with service endpoints, built-in marathon runtime, etc. The purpose of this task is to evaluate DC/OS 1.10 and identify constructs required for deploying WSO2 API Manager using Marathon.

[1] https://github.com/wso2/mesos-artifacts

**Affected Product Version:**
2.1.0.1

**Comment by imesh** [comment]
This task was done in pull request #2 and please find the results below:

- Container to container communication is available in DC/OS v1.10 with overlay networking
- The overlay network has been implemented using [Minuteman](https://github.com/dcos/minuteman) a layer 4 load balancer
- Marathon runtime is now built into DC/OS, does not need to install separately
- Service discovery can be done using service endpoints
- Service to service internal communication can be done via service endpoints and it supports HTTP and TCP.
- Volume mounts can be used for mounting configuration files and synchronizing runtime artifacts (for deployment synchronization) 

Things to do:
- Verify the compatibility of [Mesos Membership Scheme](https://github.com/wso2/mesos-artifacts/tree/master/common/mesos-membership-scheme) which was implemented for DC/OS v1.7

**Comment by DilanUA** [comment]
Closing this as we would be archiving this repo due to no recent usage.
