### ISSUE TITLE
Improve README documentation of DC/OS resources - WSO2 API Manager - pattern-1

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/dcos-apim#5]
**Description:**
Currently, the getting started [guide](https://github.com/wso2/dcos-apim/blob/master/pattern-1/README.md) for WSO2 API Manager pattern 1 provides steps at an abstract level.

When following some of the steps, often a user is required to deviate from the guide and find the relevant, concrete steps in order to complete the original step in the guide.

Thus, the README.md documentation requires improvements. A reference guide can be found from [here](https://github.com/wso2/mesos-artifacts/blob/master/wso2am/README.md).

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**
chirangaalwis

**Affected Product Version:**
2.1.0.1

**Comment by DilanUA** [comment]
Closing this as we would be archiving this repo due to no recent usage.
